apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zinde-xyz
  namespace: zinde
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`zinde.xyz`) || Host(`www.zinde.xyz`)
    services:
    - name: zinde-xyz
      port: 3000
